services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - rate-limiter-net

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - rate-limiter-net

networks:
  rate-limiter-net:
    driver: bridge
